GithubActionsDemoApp/Models/ErrorViewModel.cs
namespace GithubActionsDemoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GithubActionsDemoApp/Models/PersonasIndex.cs
using GithubActionsDemoApp.Entidades;

namespace GithubActionsDemoApp.Models
{
    public class PersonasIndex
    {
        public IEnumerable<Persona> Personas { get; set; } = new List<Persona>();
    }
}

GithubActionsDemoApp/Controllers/HomeController.cs
using GithubActionsDemoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GithubActionsDemoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GithubActionsDemoApp/Controllers/PersonasController.cs
using GithubActionsDemoApp.Entidades;
using GithubActionsDemoApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GithubActionsDemoApp.Controllers
{
    public class PersonasController : Controller
    {
        private readonly ApplicationDbContext context;

        public PersonasController(ApplicationDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var personas = await context.Personas.ToListAsync();
            var modelo = new PersonasIndex()
            {
                Personas = personas
            };
            return View(modelo);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Persona persona)
        {
            if (!ModelState.IsValid)
            {
                return View(persona);
            }

            context.Add(persona);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var persona = await context.Personas.FirstOrDefaultAsync(x => x.Id == id);

            if (persona is null)
            {
                return RedirectToAction("Index");
            }

            return View(persona);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Persona persona)
        {
            if (!ModelState.IsValid)
            {
                return View(persona);
            }

            context.Update(persona);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Borrar(int id)
        {
            var persona = await context.Personas.FirstOrDefaultAsync(x => x.Id == id);

            if (persona is null)
            {
                return RedirectToAction("Index");
            }

            return View(persona);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarPersona(int id)
        {
            await context.Personas.Where(x => x.Id == id).ExecuteDeleteAsync();
            return RedirectToAction("Index");
        }
    }
}

GithubActionsDemoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido a Github Actions - Pull Request 2</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GithubActionsDemoApp/Views/Personas/Borrar.cshtml
@model Persona
@using GithubActionsDemoApp.Entidades

@{
    ViewData["Title"] = "Borrar tipo cuenta";
}

<h3 class="mb-3">¿Está seguro que desea borrar a la persona @Model.Nombre?</h3>

<form asp-action="BorrarPersona">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

GithubActionsDemoApp/Views/Personas/Crear.cshtml
@model Persona
@using GithubActionsDemoApp.Entidades

@{
    ViewData["Title"] = "Crear Persona";
}

<h2>Crear Persona</h2>

<form asp-action="Crear">
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GithubActionsDemoApp/Views/Personas/Editar.cshtml
@model Persona
@using GithubActionsDemoApp.Entidades

@{
    ViewData["Title"] = "Editar Persona";
}

<h1>Editar Persona: @Model.Nombre</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-action="Editar">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GithubActionsDemoApp/Views/Personas/Index.cshtml
@model PersonasIndex

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>Listado de Personas</h2>

<div>
    <a class="btn btn-primary" asp-action="Crear">Crear nueva persona</a>
</div>

@if (Model.Personas.Any())
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var persona in Model.Personas)
            {
                <tr>
                    <td>
                        @persona.Nombre
                    </td>
                    <td>
                        <a class="me-2 btn btn-primary" asp-action="Editar" asp-route-id="@persona.Id">Editar</a>
                        <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@persona.Id">Borrar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No hay personas para mostrar...</p>
}

GithubActionsDemoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GithubActionsDemoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GithubActionsDemoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GithubActionsDemoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GithubActionsDemoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>